### ISSUE TITLE
Adding #define all(x) to template

### ISSUE THREAD

**Issue by lightseba** [ucf-programming-team/hackpack-cpp#12]
So I think it's generally good to keep the number of macros and typedefs in the hackpack minimal (since people like/don't like certain ones). With that said, IMO `#define all(x) begin(x), end(x)` is really useful, since it's a) readable, b) works on both STL containers and normal arrays, and c) can shorten code significantly. 

Examples:
- reversing a vector `vec`: `reverse(vec.begin(), vec.end())` becomes `reverse(all(vec))`
- sorting a primitive array `arr`: `sort(arr, arr + N)` becomes `sort(all(arr))`
- inserting all of set `mySet` at the end of vector `vec`: `vec.insert(vec.end(), mySet.begin(), mySet.end())` becomes `vec.insert(vec.end(), all(mySet))`
- clearing a vector `vec`: `fill(vec.begin(), vec.end(), 0)` becomes `fill(all(vec), 0)` (I know `vec.assign(0)` exists, but [it's slower](https://stackoverflow.com/questions/8848575/fastest-way-to-reset-every-value-of-stdvectorint-to-0#comment53876135_8849789))

thoughts/comments/objections?

**Comment by cameroncuster** [comment]
This is pretty good reasoning.

**Comment by JakeSteinebronn** [comment]
> This is pretty good reasoning.

I agree with this statement

**Comment by TylerMathis** [comment]
> > This is pretty good reasoning.
> 
> 
> 
> I agree with this statement 

I agree with this agreement.
